config:
  credentials:
  - id: sqaaas_tmp_cred-squeaky-beige-deer
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/orviz/sqaaas-paper:
      branch: master
      credential_tmp: true
      credentials_id: sqaaas_tmp_cred-squeaky-beige-deer
      repo: https://github.com/orviz/sqaaas-paper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/orviz/sqaaas-paper git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-grey-cow.sh
        container: qc.acc_lousy-olive-zebra
  QC.Doc:
    repos:
      github.com/orviz/sqaaas-paper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-eggplant-burmese.sh
        container: qc.doc_sleepy-sapphire-tortoise
      github.com/orviz/sqaaas-paper git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-rust-chow.sh
        container: qc.doc_hasty-cornflower-eleuth
      github.com/orviz/sqaaas-paper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-purple-stoat.sh
        container: qc.doc_tasty-beige-boar
  QC.Lic:
    repos:
      github.com/orviz/sqaaas-paper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.randy-platinum-guppy.sh
        container: qc.lic_nerdy-lavender-coyote
  QC.Ver:
    repos:
      github.com/orviz/sqaaas-paper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-salmon-horse.sh
        container: qc.ver_shaky-lemon-harrier
timeout: 5400
