config:
  credentials:
  - id: sqaaas_tmp_cred-cranky-copper-echidna
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/orviz/sqaaas-paper:
      branch: master
      credentials_id: sqaaas_tmp_cred-cranky-copper-echidna
      repo: https://github.com/orviz/sqaaas-paper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/orviz/sqaaas-paper git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-khaki-wallaby.sh
        container: qc.acc_crabby-lavender-mandrill
  QC.Doc:
    repos:
      github.com/orviz/sqaaas-paper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-carmine-oriole.sh
        container: qc.doc_ready-linen-wolfhound
      github.com/orviz/sqaaas-paper git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-heliotrope-scorpion.sh
        container: qc.doc_ready-russet-neanderthal
      github.com/orviz/sqaaas-paper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-maroon-centipede.sh
        container: qc.doc_shaky-scarlet-weasel
  QC.Lic:
    repos:
      github.com/orviz/sqaaas-paper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-champagne-buzzard.sh
        container: qc.lic_bluesy-red-cow
  QC.Ver:
    repos:
      github.com/orviz/sqaaas-paper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-plum-cockroach.sh
        container: qc.ver_snappy-silver-fousek
timeout: 5400
