config:
  credentials:
  - id: sqaaas_tmp_cred-homey-aquamarine-gopher
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/orviz/sqaaas-paper:
      branch: master
      credential_tmp: true
      credentials_id: sqaaas_tmp_cred-homey-aquamarine-gopher
      repo: https://github.com/orviz/sqaaas-paper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/orviz/sqaaas-paper git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-beige-cichlid.sh
        container: qc.acc_shaggy-emerald-uakari
  QC.Doc:
    repos:
      github.com/orviz/sqaaas-paper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-amethyst-forest.sh
        container: qc.doc_hasty-russet-baboon
      github.com/orviz/sqaaas-paper git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-taupe-orangutan.sh
        container: qc.doc_chewy-fuchsia-coyote
      github.com/orviz/sqaaas-paper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-carmine-penguin.sh
        container: qc.doc_surly-black-moth
  QC.Lic:
    repos:
      github.com/orviz/sqaaas-paper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-sapphire-coyote.sh
        container: qc.lic_tacky-asparagus-chipmunk
  QC.Ver:
    repos:
      github.com/orviz/sqaaas-paper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-carmine-sponge.sh
        container: qc.ver_shaggy-orchid-mule
timeout: 5400
