config:
  credentials:
  - id: sqaaas_tmp_cred-flaky-turquoise-mist
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/orviz/sqaaas-paper:
      branch: master
      credential_tmp: true
      credentials_id: sqaaas_tmp_cred-flaky-turquoise-mist
      repo: https://github.com/orviz/sqaaas-paper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/orviz/sqaaas-paper git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-seashell-otter.sh
        container: qc.acc_wiggy-burgundy-boar
  QC.Doc:
    repos:
      github.com/orviz/sqaaas-paper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-plum-crane.sh
        container: qc.doc_muzzy-smalt-swan
      github.com/orviz/sqaaas-paper git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-linen-hyena.sh
        container: qc.doc_homey-cornflower-hummingbird
      github.com/orviz/sqaaas-paper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-dandelion-birman.sh
        container: qc.doc_cheeky-pink-wildebeest
  QC.Lic:
    repos:
      github.com/orviz/sqaaas-paper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homely-malachite-monster.sh
        container: qc.lic_surly-fuchsia-emu
  QC.Ver:
    repos:
      github.com/orviz/sqaaas-paper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-smalt-hornet.sh
        container: qc.ver_dorky-bronze-mammoth
timeout: 5400
