config:
  credentials:
  - id: sqaaas_tmp_cred-craggy-gamboge-sponge
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/orviz/sqaaas-paper:
      branch: master
      credential_tmp: true
      credentials_id: sqaaas_tmp_cred-craggy-gamboge-sponge
      repo: https://github.com/orviz/sqaaas-paper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/orviz/sqaaas-paper git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-khaki-chamois.sh
        container: qc.acc_boozy-chartreuse-beetle
  QC.Doc:
    repos:
      github.com/orviz/sqaaas-paper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-goldenrod-weasel.sh
        container: qc.doc_pokey-orchid-bird
      github.com/orviz/sqaaas-paper git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-brown-malamute.sh
        container: qc.doc_hilly-beige-dhole
      github.com/orviz/sqaaas-paper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-amethyst-ocelot.sh
        container: qc.doc_baggy-taupe-crane
  QC.Lic:
    repos:
      github.com/orviz/sqaaas-paper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-flax-dragon.sh
        container: qc.lic_pretty-crimson-rhinoceros
  QC.Ver:
    repos:
      github.com/orviz/sqaaas-paper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-harlequin-meerkat.sh
        container: qc.ver_foggy-gamboge-bonobo
timeout: 5400
